name: allure-report

on:
  workflow_dispatch:

jobs:
  allure:
    name: Generate Report
    runs-on: ubuntu-latest
    steps:
      # - name: Setup Docker MacOS
      #   run: |
      #     brew install docker
      #     colima start

      - uses: actions/checkout@v2

      - name: Get history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Report action from marketplace
        uses: firmanrosid/mochawesome-report-action@master
        if: always()
        #id: allure-report
        with:
          subfolder: smoke
          report_history: report-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: report-history
